config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }

  root "categories#index"

  resources :categories, only: [:show]
  resources :products, only: [:index, :show]

  resources :carts, only: [:show, :destroy] 
  get 'carts', to: 'carts#add_product_carts'
  get 'update_quantity', to: 'carts#update_quantity'
  get 'empty_cart', to: 'shared#empty_cart'
  get 'place_order', to: 'carts#place_order'
  post 'verify_payment', to: 'carts#verify_payment'
  get 'my_orders', to: 'carts#my_orders'
  get 'view_order_detail', to: 'carts#view_order_detail'
  
  resources :wishlists, only: [:show, :create, :destroy] 

  resources :profiles, only: [:show, :index]
  post 'update_profile', to: 'profiles#update_profile'

  post 'notify_users', to: 'notify_users#notify_users'

  get 'search', to: "categories#search"
  get 'filter', to: "products#search"
  

end

app/models/cart.rb
class Cart < ApplicationRecord
	
	enum :status, { in_cart: 0, placed: 1, delivered: 2, cancelled: 3 }

	has_many :product_carts, dependent: :destroy
	has_many :products, through: :product_carts
	belongs_to :user

	accepts_nested_attributes_for :product_carts

	after_update :send_delivered_or_cancelled_mail, if: :saved_change_to_status?

	private

	def send_delivered_or_cancelled_mail
		if self.status == "delivered"
			UserMailMailer.delivered_order_confirmation(user, self).deliver_now
		elsif self.status == "cancelled"
			UserMailMailer.cancelled_order_confirmation(user, self).deliver_now
		end	
	end
		
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	skip_before_action :verify_authenticity_token, only: [:verify_payment]
	before_action :find_cart, except: [:my_orders, :view_order_detail]

	def show
	end

	def add_product_carts
    product = Product.where('id = ? AND stock > ?', params[:product_id], 0).first
    if product.present?
    	@cart = Cart.find_or_create_by(user_id: current_user.id, status: 'in_cart' )
    	@cart.product_carts.create(product_id: product.id, quantity:1, unit_price: product.price, total_price: product.price)
    	product.update_attribute(:stock, product.stock - 1)
    	update_cart_value
    	redirect_to cart_path(@cart)
    else
    	flash[:notice] = "product is not present"
    	redirect_to root_path
    end	
	end
	
	def destroy
		product_cart = @cart.product_carts.find_by(id: params[:product_cart_id])
		product_cart.destroy
		if @cart.product_carts.empty?
  		redirect_to empty_cart_path(message: "Your cart is now empty.") 
		else
  		redirect_to cart_path(@cart)
		end		
	end

	def update_quantity
		product = Product.find_by(id: params[:product_id])
		product_cart = @cart.product_carts.find_by(product_id: params[:product_id])
		if params[:new_quantity] > params[:old_quantity] && product.stock > 0
			product_cart.update(quantity: params[:new_quantity], total_price: params[:new_quantity].to_i * product_cart.unit_price)
			product.update_attribute(:stock, product.stock - 1)
		elsif
			product_cart.update(quantity: params[:new_quantity], total_price: params[:new_quantity].to_i * product_cart.unit_price)
			product.update_attribute(:stock, product.stock + 1)
		else
			flash[:notice] = "product is not present"
			redirect_to root_path
		end
		update_cart_value
		redirect_to cart_path(@cart) 
	end

	def place_order
    receipt = "Order-#{Time.now.to_i}"
	  razorpay_order = Payment::RazorpayPayments.new.create_order(@cart.total, receipt)
    if razorpay_order.status == 'created'
		  @cart.update_columns(razorpay_order_id: razorpay_order.id, razorpay_payment_status: razorpay_order.status)
		else
			flash[:notice] = 'something went wrong'
  	  redirect_to root_path
  	end
		render 'carts/payment', locals: { cart: @cart } and return
	end

	def verify_payment
		res = { razorpay_order_id: params[:razorpay_order_id],
		razorpay_payment_id: params[:razorpay_payment_id],
    razorpay_signature: params[:razorpay_signature] } 
		if Payment::RazorpayPayments.new.verify_payment(res)
			razorpay_payment_id = params[:razorpay_payment_id]
			para_attr = {
    	"amount": @cart.total*100,
    	"currency": "INR"
			}
			capture_status = Payment::RazorpayPayments.new.capture_payment(razorpay_payment_id, para_attr)
			@cart.update_columns(razorpay_payment_id: params[:razorpay_order_id], razorpay_payment_status: 'captured', status: 'placed' )
			UserMailMailer.placed_order_confirmation(current_user, @cart).deliver_now
			flash[:notice] = "payment successfull"
    	redirect_to root_path
		else
			flash[:notice] = "something went wrong"
			redirect_to cart_path(id: @cart.id)
		end
	end

	def my_orders
		@orders = Cart.where.not(status: 'in_cart')
	end

	def view_order_detail
		@view_order = Cart.find_by(id: params[:id])	
	end

	private

	def update_cart_value
		subtotal = @cart.product_carts.sum('total_price')
		if ShippingCharge.first.present? && subtotal < ShippingCharge.first&.total_is_grater_than.to_i
			shipping_charge = ShippingCharge.first.shipping_charge
			@cart.update(subtotal: subtotal, shipping_cost:shipping_charge, total: subtotal + shipping_charge)
		else
		  @cart.update(subtotal: subtotal, shipping_cost: 0, total: subtotal)
		end
	end

	def find_cart
		@cart = Cart.find_by(id: params[:id])
	end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/my_orders.html.erb
<div class="row">
	<% @orders.each do |order|  %>
		<div class=" ms-5 card text-center " style="width: 22rem;">
			<% product = order.product_carts.first.product %>
			<div class= mt-4>
				<% if product.cover.present? %>
		    	<%= link_to (image_tag product.cover, :size => '195x160'), product_path(id: product.id) %>
		  	<% end %>
	  	</div>
			<div class="card-body text-center mx-auto">
		   	<p class="card-text">Payment Id: <%= order.razorpay_payment_id %></p>
		    <p class="card-text">Order Id: <%= order.razorpay_order_id %></p>
		    <p class="card-text">Payment status: <%= order.razorpay_payment_status %></p>
		    <p class="card-text">Order status: <%= order.status %></p>
		    <p class="card-text">Amount: <%= order.total %></p>
		    <p class="card-text"><%= link_to "detail",view_order_detail_path(id: order.id), class: "btn btn-success" %></p>
		  </div>
		</div>
	<% end %>
</div>

app/views/carts/payment.html.erb
<button id="rzp-button1" type="button" class="btn btn-primary ">Bye now</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": 'rzp_test_CzInVsmPYOMFQA', // Enter the Key ID generated from the Dashboard
    "amount": "50000", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
    "currency": "INR",
    "name": "Acme Corp",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "<%= cart.razorpay_order_id %>", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "callback_url": "/verify_payment?id=<%= cart.id %>",
    "prefill": {
        "name": "Gaurav Kumar",
        "email": "gaurav.kumar@example.com",
        "contact": "9000090000"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>

app/views/carts/show.html.erb
<% @cart.product_carts.each do |product_cart| %>
  <% product = product_cart.product %>
  <div class="card rounded-3 mb-4 mx-5 ">
    <div class="card-body p-4">
      <div class="row d-flex justify-content-between align-items-center">
        <div class="col-md-2 col-lg-2 col-xl-2 text-center">
          <% if product.cover.present? %>
        <%= link_to (image_tag product.cover, :size => '195x160'), product_path(id: product.id) %>
        <% end %>
        <p class="lead fw-normal mb-2 text-center"><%= product.name %></p>
        </div>
        <div class="col-md-3 col-lg-3 col-xl-3">
          <p class="lead fw-normal ms-5"><%= product_cart.unit_price %>Rs</p>
        </div>      
        <div class="d-flex mb-4" style="max-width: 200px">
          <button class="btn btn-primary px-3 me-2"
            onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
            <%= link_to update_quantity_path(id: @cart.id, product_id: product.id, old_quantity:product_cart.quantity, new_quantity: product_cart.quantity-1) do %>
            <i class="bi bi-file-minus text-light" ></i>
            <% end %>
          </button>
          <div class="form-outline">
            <input id="form1" min="0" name="quantity" value="<%= product_cart.quantity
             %>" type="number" class="form-control" >
          </div>
          <button class="btn btn-primary px-3 ms-2"
            onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
            <%= link_to update_quantity_path(id: @cart.id, product_id: product.id, old_quantity:product_cart.quantity, new_quantity: product_cart.quantity+1) do %>
            <i class="bi bi-file-plus text-light"></i>
            <% end %>
          </button>
        </div>
        <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
          <h5 class="mb-0"><%= product_cart.total_price %>Rs</h5>
        </div>
        <div class="col-md-1 col-lg-1 col-xl-1 text-end">
          <%= link_to cart_path(id: @cart.id, product_cart_id: product_cart.id), data: {turbo_method: :delete} do %>
            <i class="fas bi-trash fa-lg"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>      
<div class="card mb-4 mx-5">
  <div class="card-header py-3">
    <h5 class="mb-0">Summary</h5>
  </div>
  <div class="card-body">
    <ul class="list-group list-group-flush">
      <li
        class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
        subtotal
        <span><%= @cart.subtotal %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center px-0">
        Shipping Charge
        <span><%= @cart.shipping_cost %></span>
      </li>
      <li
        class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
        <div>
          <strong>Total amount</strong>
          <strong>
            <p class="mb-0">(includin charges)</p>
          </strong>
        </div>
          <span><strong><%= @cart.total %></strong></span>
      </li>
    </ul>

    <button type="button" class="btn btn-primary ">
      <%= link_to "Place Order", place_order_path(id: @cart.id), class: "btn btn-primary " %>
    </button>
  </div>
</div>


        

        

       

app/views/carts/view_order_detail.html.erb
<% @view_order.product_carts.each do |product_cart| %>
	<% product = product_cart.product %>
	<div class="card rounded-3 mb-4 mx-5 ">
	    <div class="card-body p-4">
	      <div class="row d-flex justify-content-between align-items-center">
	        <div class="col-md-2 col-lg-2 col-xl-2 text-center">
	        	<% if product.cover.present? %>
	        		<%= link_to (image_tag product.cover, :size => '195x160'), product_path(id: product.id) %>
	        	<% end %>
	        <p class="lead fw-normal mb-2 text-center"><%= product.name %></p>
	        </div>
	        <div class="col-md-3 col-lg-3 col-xl-3">
	          <p class="lead fw-normal ms-5"><%= product_cart.unit_price %></p>
	        </div>
	        <div class="col-md-3 col-lg-3 col-xl-3">
	          <p class="lead fw-normal ms-5"><%= product_cart.quantity %></p>
	        </div>      
	        <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
	          <h5 class="mb-0"><%= product_cart.total_price %></h5>
	        </div>
	      </div>
	    </div>
	  </div>
<% end %>
<div class="card mb-4 mx-5">
  <div class="card-header py-3">
    <h5 class="mb-0">Summary</h5>
  </div>
  <div class="card-body">
    <ul class="list-group list-group-flush">
      <li
        class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
        subtotal
        <span><%= @view_order.subtotal %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center px-0">
        Shipping Charge
        <span><%= @view_order.shipping_cost %></span>
      </li>
      <li
        class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
        <div>
          <strong>Total amount</strong>
          <strong>
            <p class="mb-0">(includin charges)</p>
          </strong>
        </div>
          <span><strong><%= @view_order.total %></strong></span>
      </li>
    </ul>
  </div>
</div>