config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }

  root "categories#index"

  resources :categories, only: [:show]
  resources :products, only: [:index, :show]

  resources :carts, only: [:show, :destroy] 
  get 'carts', to: 'carts#add_product_carts'
  get 'update_quantity', to: 'carts#update_quantity'
  get 'empty_cart', to: 'shared#empty_cart'
  get 'place_order', to: 'carts#place_order'
  post 'verify_payment', to: 'carts#verify_payment'
  get 'my_orders', to: 'carts#my_orders'
  get 'view_order_detail', to: 'carts#view_order_detail'
  
  resources :wishlists, only: [:show, :create, :destroy] 

  resources :profiles, only: [:show, :index]
  post 'update_profile', to: 'profiles#update_profile'

  post 'notify_users', to: 'notify_users#notify_users'

  get 'search', to: "categories#search"
  get 'filter', to: "products#search"
  

end

app/models/category.rb
class Category < ApplicationRecord

	validates :image, presence: true
	validates :name, presence: true, uniqueness: true

	has_many :products, dependent: :destroy

	has_one_attached :image
	
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_blocked_user
  before_action :authenticate_user!

  def index
    @categories = Category.order(:name)
  end

  def search
    @categories = Category.where("categories.name LIKE ?", "%" + params[:q] + "%")
    @products = Product.where("products.name LIKE ?", "%" + params[:q] + "%")
    render :index
  end
  
  private

  def check_blocked_user
    if current_user.present? && current_user.blocked?
      sign_out current_user
      flash[:notice] = "Your account has been blocked."
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<% if !flash[:notice].blank? %>
	<div class = "notice">
		<%= flash[:notice] %>
	</div>
<% end %>

<h2 class= "ms-5 mb-4 mt-5">Categories</h2>
<div class="row">
	<% @categories.each do |category| %>
		<div class=" ms-5 card " style="width: 12rem;">
			<div class="card-body text-center mx-auto">
		  <% if category.image.present? %>
		  <%= link_to (image_tag category.image, :size => '136x150'), products_path(category_id: category.id) %>
		  <% end %>
		    <h5 class="card-title"><%= category.name %></h5>
		  </div>
		</div>
	<% end %>
</div>

<h2 class= "ms-5 mb-5 mt-5">All Products</h2>
<div class="row">
	<% products = !!defined?(@products) ? @products : Product.all %>
	<% products.each do |product| %>
		<div class=" ms-5 card " style="width: 12rem;">
			<% wishlist = current_user.wishlist %>
			<% if wishlist.present? && wishlist.wishlist_items.find_by(product_id: product.id).present? %>
				<%= link_to wishlist_path(id: wishlist.id, product_id: product.id), data: {turbo_method: :delete} do %>
					<i class="bi bi-heart-fill text-danger" style=" position: absolute; top: -1px; right: 4px; z-index: 1; font-size:20px;"></i>
				<% end %>
			<% else %>	
				<%= link_to wishlists_path(product_id: product.id), data: { turbo_method: "post" } do %>
				<i class="bi bi-heart text-danger" style=" position: absolute; top: -1px; right: 4px; z-index: 1; font-size:20px;"></i>
				<% end %>
			<% end %>	
			<div class="card-body text-center mx-auto">
		 		<% if product.cover.present? %>
			  <%= link_to (image_tag product.cover, :size => '136x150'), product_path(id: product.id) %>
			  <% end %>
		    <h5 class="card-title"><%= product.name %></h5>
		  </div>  
		</div>
	<% end %>
</div>