config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }

  root "categories#index"

  resources :categories, only: [:show]
  resources :products, only: [:index, :show]

  resources :carts, only: [:show, :destroy] 
  get 'carts', to: 'carts#add_product_carts'
  get 'update_quantity', to: 'carts#update_quantity'
  get 'empty_cart', to: 'shared#empty_cart'
  get 'place_order', to: 'carts#place_order'
  post 'verify_payment', to: 'carts#verify_payment'
  get 'my_orders', to: 'carts#my_orders'
  get 'view_order_detail', to: 'carts#view_order_detail'
  
  resources :wishlists, only: [:show, :create, :destroy] 

  resources :profiles, only: [:show, :index]
  post 'update_profile', to: 'profiles#update_profile'

  post 'notify_users', to: 'notify_users#notify_users'

  get 'search', to: "categories#search"
  get 'filter', to: "products#search"
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, ActiveAdmin::Page, :name => "Dashboard"
    if user.role == 'admin'
      can :manage, :all
    elsif user.role == 'delivery_boy'
      can :manage, Cart
    elsif user.role == 'vendor'
      can :manage, Product
      can :manage, ProductCart  
    end
    
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  has_many :products       

  enum :role, { admin: 0, delivery_boy: 1, vendor: 2 }       
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  primary_abstract_class
  
end

app/models/cart.rb
class Cart < ApplicationRecord
	
	enum :status, { in_cart: 0, placed: 1, delivered: 2, cancelled: 3 }

	has_many :product_carts, dependent: :destroy
	has_many :products, through: :product_carts
	belongs_to :user

	accepts_nested_attributes_for :product_carts

	after_update :send_delivered_or_cancelled_mail, if: :saved_change_to_status?

	private

	def send_delivered_or_cancelled_mail
		if self.status == "delivered"
			UserMailMailer.delivered_order_confirmation(user, self).deliver_now
		elsif self.status == "cancelled"
			UserMailMailer.cancelled_order_confirmation(user, self).deliver_now
		end	
	end
		
end

app/models/category.rb
class Category < ApplicationRecord

	validates :image, presence: true
	validates :name, presence: true, uniqueness: true

	has_many :products, dependent: :destroy

	has_one_attached :image
	
end

app/models/category_csv.rb
require 'csv'
class CategoryCsv
  class << self
    def convert_save(model_name, csv_data)
      csv_file = csv_data.read
      lines = CSV.parse(csv_file)
      header = lines.shift
      failed_instances = []
      count = 0
      notice = ''
      lines.each_with_index do |line, index|
        attributes = Hash[header.zip line]
        target_model = model_name.classify.constantize
        image_data = attributes.delete("image")
        instance = target_model.new(attributes)
        instance.image.attach(io: File.open(image_data), filename: File.basename(image_data)) if image_data.present?
        if instance.save
        	count += 1
        else
          failed_instances << { instance: instance, line_number: index + 2 }
        	error_messages = failed_instances.map { |failed_instance| "Line #{failed_instance[:line_number]}: #{failed_instance[:instance].errors.full_messages.join(', ')}"}
        		notice = "Some instances could not be saved: #{error_messages}"
        end    	
      end
      [count, notice]
    end
  end
end

app/models/notify_user.rb
class NotifyUser < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord

	#validates :description, :stock, :price, :cover, :images, presence: true
	#validates :name, uniqueness: { case_sensitive: false }

	default_scope {where(hide: false)}

	has_one_attached :cover
	has_many_attached :images 

	belongs_to :category
	has_many :product_carts, dependent: :destroy 
	has_many :carts, through: :product_carts
	has_many :wishlist_items, dependent: :destroy 
	has_many :wishlists, through: :wishlist_items
	has_many :notify_users

	belongs_to :admin_user

	after_update :notify_user_after_stock_update, if: :saved_change_to_stock?

	private

	def notify_user_after_stock_update
		UserMailMailer.notify_when_stock_update(self.notify_users.pluck(:user_id), self
    ).deliver_now
    self.notify_users.destroy_all
	end
	
end

app/models/product_cart.rb
class ProductCart < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  before_destroy :add_stock_to_product
  after_destroy :destroy_cart_if_no_product_present
  after_update :check_status

  enum :status, { not_delivered: 0, delivered: 1, cancelled: 2 }

  private

  def add_stock_to_product
    product.update_attribute(:stock, product.stock + quantity)   
  end

  def destroy_cart_if_no_product_present
    if cart.product_carts.empty?
      cart.destroy
    end
  end


  def check_status
    if self.cart.product_carts.where.not(status: 'delivered').none?
      self.cart.update(status: 'delivered')
    end
  end

end
 

app/models/product_csv.rb
require 'csv'
class ProductCsv < ApplicationRecord
	class << self
    def convert_save(model_name, csv_data)
      csv_file = csv_data.read
      lines = CSV.parse(csv_file)
      header = lines.shift
      failed_instances = []
      count = 0
      notice = ''
      lines.each_with_index do |line, index|
        attributes = Hash[header.zip line]
        target_model = model_name.classify.constantize
        category = Category.find_by("lower(name) = ?", attributes["category"].downcase)
        cover_image = attributes.delete("cover")
        instance = target_model.new(name:attributes["name"], description:attributes["description"], stock:attributes["stock"], price:attributes["price"], category_id: category.id)       
        instance.cover.attach(io: File.open(cover_image), filename: File.basename(cover_image)) if cover_image.present?
      
        images = attributes.delete("images")&.split(",")
        if images.present?
          images.each do |image|
          	instance.images.attach(io: File.open(image), filename: File.basename(image))
          end
        end
        if instance.save
        	count += 1
        else
          failed_instances << { instance: instance, line_number: index + 2 }
        	error_messages = failed_instances.map { |failed_instance| "Line #{failed_instance[:line_number]}: #{failed_instance[:instance].errors.full_messages.join(', ')}"}
        		notice = "Some instances could not be saved: #{error_messages}"
        end    	
      end 
      [count, notice]
    end
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user
	has_one_attached :image
end

app/models/shipping_charge.rb
class ShippingCharge < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

  has_many :carts, dependent: :destroy
  has_one :wishlist, dependent: :destroy
  has_many :notify_users, dependent: :destroy
  has_one :profile, dependent: :destroy

  after_create :create_profile

  private

  def create_profile
    Profile.find_or_create_by(user_id: self.id)
  end
  
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord

	belongs_to :user
	has_many :wishlist_items
	has_many :products, through: :wishlist_items
	
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
	
	belongs_to :product
	belongs_to :wishlist

	after_destroy :destroy_wishlist_if_no_product_present

	private

	def destroy_wishlist_if_no_product_present
    if wishlist.wishlist_items.empty?
      wishlist.destroy
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
    @category = Category.find_by(id: params[:category_id])
    @products = @category.products
  end

  def show
    @product = Product.find_by(id: params[:id])
  end

  def search
    @products = Product.where("products.name LIKE ?", "%" + params[:q] + "%")
    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/admin/csv/products/product_import_csv.html.erb
<%= form_for :dump, :url=>{:action=>"upload_csv"}, :html => { :multipart => true } do |f| %>
  <table>
    <tr>
      <td>
        <label for = "dump_file">
          <%= f.file_field :file %>
        </label>
      </td>
    </tr>
    <tr>
      <td>
        <%= submit_tag 'Submit' %>
      </td>
    </tr>
  </table>  
<% end %>

app/views/products/index.html.erb
<div class="row">
	<% @products.each do |product| %>
		<div class=" ms-5 card " style="width: 16rem;">
			<% wishlist = current_user.wishlist %>
			<% if wishlist.present? && wishlist.wishlist_items.find_by(product_id: product.id).present? %>
				<%= link_to wishlist_path(id: wishlist.id, product_id: product.id), data: {turbo_method: :delete} do %>
					<i class="bi bi-heart-fill text-danger" style=" position: absolute; top: -4px; right: 3px; z-index: 1; font-size:25px;"></i>
				<% end %>
			<% else %>	
				<%= link_to wishlists_path(product_id: product.id), data: { turbo_method: "post" } do %>
				<i class="bi bi-heart text-danger" style=" position: absolute; top: -4px; right: 3px; z-index: 1; font-size:25px;"></i>
				<% end %>
			<% end %>
			<div class="card-body text-center">
			  <% if product.cover.present? %>
			  	<%= link_to (image_tag product.cover, :size => '195x160'), product_path(id: product.id) %>
			  <% end %>
		    <h5 class="card-title"><%= product.name %></h5>
		    <p class="card-text"><%= product.price %> INR</p>
		    <% cart = current_user.carts.find_by(status: 'in_cart') %>
		    <% if cart.present? && cart.product_carts.find_by(product_id: product.id).present? %>
		    	<%= link_to "Go to Cart", cart_path(id: cart.id) ,class: "btn btn-success" %>
		    <% elsif product.stock <= 0 %>
		    	<a><%= link_to "Notify Me", notify_users_path(product_id:product.id, user_id: current_user.id ) ,class: "btn btn-success #{'disabled' if product.notify_users.where(user_id: current_user.id, product_id: product.id).present?}", data: { turbo_method: "post" }  %></a>
		    <% else  %>
		    	<%= link_to "Add To Cart", carts_path(product_id: product.id),class: "btn btn-success " %>
		    <% end %>
		  </div>  
		</div>
	<% end %>
</div>

app/views/products/show.html.erb
<div class="card mx-auto text-center" style="width: 40rem; height: 45rem;">
	<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
	  <div class="carousel-inner">
	  	<div class="mt-5">
		    <% if @product.images.present? %>
		      <%  @product.images.each_with_index do |image, index| %>
			      <div class="carousel-item <%= 'active' if index == 0 %>">
							<%= image_tag image, :size => '620x400' %>
						</div>	
					<% end %>
				<% end %>
			</div>
	  </div>
	  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
	    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	    <span class="visually-hidden">Previous</span>
	  </button>
	  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
	    <span class="carousel-control-next-icon" aria-hidden="true"></span>
	    <span class="visually-hidden">Next</span>
	  </button>
	</div>
	<% wishlist = current_user.wishlist %>
	<% if wishlist.present? && wishlist.wishlist_items.find_by(product_id: @product.id).present? %>
		<%= link_to wishlist_path(id: wishlist.id, product_id: @product.id), data: {turbo_method: :delete} do %>
			<i class="bi bi-heart-fill text-danger" style=" position: absolute; top: -1px; right: 4px; z-index: 1; font-size:25px;"></i>
		<% end %>
	<% else %>	
		<%= link_to wishlists_path(product_id: @product.id), data: { turbo_method: "post" } do %>
			<i class="bi bi-heart text-danger" style=" position: absolute; top: -1px; right: 4px; z-index: 1; font-size:25px;"></i>
		<% end %>
	<% end %>
	<div class="card-body">
		<h5 class="card-title"><%= @product.name %></h5>
		<p class="card-text"><%= @product.description %></p>
		<p class="card-text"><%= @product.price %> INR</p>
		<% cart = current_user.carts.find_by(status: 'in_cart') %>
    <% if cart.present? && cart.product_carts.find_by(product_id: @product.id).present?  %>
    	<%= link_to "Go to Cart", cart_path(id: cart.id) ,class: "btn btn-success" %>
    <% elsif @product.stock <= 0 %>
		  <a><%= link_to "Notify Me", notify_users_path(product_id:@product.id, user_id: current_user.id ) ,class: "btn btn-success #{'disabled' if @product.notify_users.where(user_id: current_user.id, product_id: @product.id).present?}", data: { turbo_method: "post" }  %></a>
    <% else  %>
    	<%= link_to "Add To Cart", carts_path(product_id: @product.id) ,class: "btn btn-success" %>
    <% end %>
	</div>
</div>